### ISSUE TITLE
cross-compilation using windows-x86: WindowsError in random.py

### ISSUE THREAD

**Issue by jcfr** [python-cmake-buildsystem/python-cmake-buildsystem#126]
```
docker run -ti -v $SRC:/usr/pysrc:ro thewtex/cross-compiler-windows-x86 bash -c '\
cp /usr/pysrc/Python-2.7.11.tgz /usr/; \
cd /usr; tar -xzvf Python-2.7.11.tgz; \
cd Python-2.7.11; \
patch -p0 -i /usr/pysrc/cmake/patches-win32/01-dynload_win.patch; \
patch -p0 -i /usr/pysrc/cmake/patches-win32/02-signalmodule.patch; \
patch -p0 -i /usr/pysrc/cmake/patches-win32/03-mingw32.patch; \
patch -p0 -i /usr/pysrc/cmake/patches-win32/04-uninitialised-flags.patch; \
mkdir /usr/build; cd /usr/build; \
cmake -DBUILD_STATIC=0 -DBUILD_SHARED=1 -DENABLE_CTYPES=0 -DENABLE_SOCKET=0 -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE ../pysrc; \
make -j4; \
ctest -R; \
bash'
```

```
1: Test command: /usr/bin/wine "/usr/build/bin/python.exe" "-Wd" "-3" "-E" "-tt" "/usr/build/Lib/test/regrtest.py" "-l" "-v" "test_abc"
1: Test timeout computed to be: 1500
1: Traceback (most recent call last):
1:   File "/usr/build/Lib/test/regrtest.py", line 160, in <module>
1:     import random
1:   File "Z:\usr\build\Lib\random.py", line 885, in <module>
1:     _inst = Random()
1:   File "Z:\usr\build\Lib\random.py", line 97, in __init__
1:     self.seed(x)
1:   File "Z:\usr\build\Lib\random.py", line 113, in seed
1:     a = long(_hexlify(_urandom(2500)), 16)
1: WindowsError: [Error -2146893801] Windows Error 0x80090017
1/1 Test #1: test_abc .........................***Failed    3.23 sec
```

**Comment by jcfr** [comment]
Cc: @thewtex

**Comment by RdeWilde** [comment]
```
Traceback (most recent call last):
File "c:/Python27/Scripts/pywin32_postinstall.py", line 9, in <module>
import tempfile
File "C:\Python27\lib\tempfile.py", line 35, in <module>
from random import Random as _Random
File "C:\Python27\lib\random.py", line 885, in <module>
_inst = Random()
File "C:\Python27\lib\random.py", line 97, in __init__
self.seed(x)
File "C:\Python27\lib\random.py", line 113, in seed
a = long(_hexlify(_urandom(2500)), 16)
WindowsError: [Error -2146893801] Windows Error 0x80090017
fixme:msvcrt:__clean_type_info_names_internal (0x100ac698) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e24d588) stub 
```
Should I just update?

**Comment by thewtex** [comment]
@RdeWilde `dockcross/windows-x86` is an updated image.
