### ISSUE TITLE
How to build with sqlite?

### ISSUE THREAD

**Issue by anki-code** [python-cmake-buildsystem/python-cmake-buildsystem#309]
Hi @jcfr!

I try to build python with sqlite:
```python
docker run --rm -it python:3.9-alpine sh

apk update && apk add --update musl-dev gcc make cmake python3-dev py3-pip chrpath git vim mc wget openssh-client libuuid build-base

mkdir /tmp/python
cd /tmp/python
mkdir -p python-build && mkdir -p python-install
git clone git://github.com/python-cmake-buildsystem/python-cmake-buildsystem
cd python-cmake-buildsystem 
cd /tmp/python/python-build

cmake -DBUILD_EXTENSIONS_AS_BUILTIN=ON -DWITH_STATIC_DEPENDENCIES=ON -DBUILTIN_OSSAUDIODEV=OFF -DENABLE_OSSAUDIODEV=OFF -DENABLE_LINUXAUDIODEV=OFF -DBUILTIN_LINUXAUDIODEV=OFF -DENABLE_AUDIOOP=OFF -DBUILTIN_AUDIOOP=OFF -DCMAKE_INSTALL_PREFIX:PATH=${HOME}/scratch/python-install ../python-cmake-buildsystem

make -j10

# But:

cd /tmp/python/python-build/bin
./python
import sqlite3
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/python/python-build/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
#    from sqlite3.dbapi2 import *
#  File "/python/python-build/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
#    from _sqlite3 import *
#ModuleNotFoundError: No module named '_sqlite3'
```

How I can get the python with statically linked sqlite?

Thanks!

**Comment by anki-code** [comment]
I missed this:
```bash
apk add sqlite-static sqlite-dev # to install /usr/lib/libsqlite3.a and /usr/include/libsqlite3.h
# and add to cmake: -DSQLite3_LIBRARIES=/usr/lib/libsqlite3.a -DSQLite3_INCLUDE_DIRS=/usr/include
```
Now it works.
